(function () {
  const ui = window.ScrapeFlowUI;
  const api = window.ScrapeFlowAPI;
  document.addEventListener("DOMContentLoaded", async () => {
    const main = ui.shell("chat", "Natural language extraction chat", "Describe the target data, let the planner update context, and use the live context panel as your control surface.");
    if (!main || !ui.requireAuth()) return;
    const params = new URLSearchParams(window.location.search);
    const projectId = params.get("project") || ui.getActiveProject()?.id;
    if (!projectId) { main.innerHTML = `<div class='empty-state'>Open a project first.</div>`; return; }
    const session = ui.currentSession();
    let conversationId = params.get("conversation") || ui.getActiveConversation()?.id;
    if (!conversationId) { const conversation = await api.createConversation({ project_id: projectId, user_id: session.id, title: "Planner chat" }); conversationId = conversation.id; ui.setActiveConversation(conversation); }
    const [project, context, messages] = await Promise.all([api.getProject(projectId), api.getProjectContext(projectId), api.getMessages(conversationId)]);
    ui.setActiveProject(project);
    let currentContext = context;
    let currentMessages = messages;
    main.innerHTML = `<section class='chat-layout'><div class='card'><div class='card-header'><p class='eyebrow'>Conversation</p><h2 style='margin:0;font-size:22px'>${project.name}</h2></div><div class='card-body section-grid'><div id='chatThread' class='chat-thread'></div><form id='chatComposer' class='composer'><textarea id='chatInput' placeholder='Extract products from https://example.com and include price, rating, and stock status'></textarea><div class='quick-actions'><button class='button-secondary' type='button' data-sample='extract laptops from https://example.com and include price and rating and export as excel'>Use sample prompt</button><button class='button' type='submit'>Send message</button></div></form></div></div><aside class='context-panel'><div class='card'><div class='card-header'><p class='eyebrow'>Live context</p><h2 style='margin:0;font-size:22px'>Planner state</h2></div><div class='card-body' id='contextPanel'></div></div><div class='card'><div class='card-body quick-actions'><a class='button-secondary' href='/plan.html?project=${projectId}'>Review plan</a><a class='button-secondary' href='/context.html?project=${projectId}'>Save context</a><a class='button' href='/jobs.html?project=${projectId}'>Run extraction</a></div></div></aside></section>`;
    const thread = main.querySelector("#chatThread");
    const contextPanel = main.querySelector("#contextPanel");
    function renderThread() { ui.renderList(thread, currentMessages, (message) => `<article class='message-bubble ${message.role === "user" ? "user" : "assistant"}'><div class='message-role'>${message.role} • ${ui.formatDate(message.created_at)}</div><p class='message-content'>${ui.escapeHtml(message.content)}</p></article>`, "Start the conversation to generate plan-ready context."); thread.scrollTop = thread.scrollHeight; }
    function renderContext() { contextPanel.innerHTML = `<div class='list'><div class='list-item'><div><div style='font-weight:700'>Target URL</div><div class='inline-meta'><span>${currentContext?.target_url || "Not set"}</span></div></div><span class='kbd'>v${currentContext?.version || 0}</span></div><div class='list-item'><div><div style='font-weight:700'>Domain</div><div class='inline-meta'><span>${currentContext?.domain || "Pending"}</span></div></div></div><div class='list-item'><div><div style='font-weight:700'>Entity</div><div class='inline-meta'><span>${currentContext?.entity || "Pending"}</span></div></div></div><div class='list-item'><div><div style='font-weight:700'>Fields</div><div class='context-chip-row'>${(currentContext?.fields || []).map((field) => `<span class='context-chip'>${field}</span>`).join("") || `<span class='context-chip'>None yet</span>`}</div></div></div><div class='list-item'><div><div style='font-weight:700'>Filters</div><div class='context-chip-row'>${(currentContext?.filters || []).map((field) => `<span class='context-chip'>${typeof field === "string" ? field : JSON.stringify(field)}</span>`).join("") || `<span class='context-chip'>None yet</span>`}</div></div></div><div class='list-item'><div><div style='font-weight:700'>Export format</div><div class='inline-meta'><span>${currentContext?.export_format || "json"}</span></div></div></div><div class='list-item'><div><div style='font-weight:700'>Summary</div><div class='inline-meta'><span>${currentContext?.summary || "Waiting for instructions"}</span></div></div></div></div>`; }
    renderThread(); renderContext();
    main.querySelector("[data-sample]").addEventListener("click", (event) => { main.querySelector("#chatInput").value = event.target.dataset.sample; });
    main.querySelector("#chatComposer").addEventListener("submit", async (event) => { event.preventDefault(); const input = main.querySelector("#chatInput"); const content = input.value.trim(); if (!content) return; try { const payload = await api.sendMessage(conversationId, { role: "user", content }); currentMessages = [...currentMessages, payload.message]; currentContext = payload.context; input.value = ""; renderThread(); renderContext(); ui.toast("Message processed and context updated.", "success"); } catch (error) { ui.toast(error.message, "error"); } });
  });
})();
