(function () {
  const ui = window.ScrapeFlowUI;
  const api = window.ScrapeFlowAPI;
  document.addEventListener("DOMContentLoaded", async () => {
    const main = ui.shell("plan", "Plan review", "Inspect the proposed extraction path before the browser runner touches the target site.");
    if (!main || !ui.requireAuth()) return;
    const projectId = new URLSearchParams(window.location.search).get("project") || ui.getActiveProject()?.id;
    if (!projectId) { main.innerHTML = `<div class='empty-state'>Open a project first.</div>`; return; }
    const [project, context, conversations] = await Promise.all([api.getProject(projectId), api.getProjectContext(projectId), api.getProjectConversations(projectId)]);
    const steps = context.current_plan?.steps || ["Open target URL", "Identify target cards", "Paginate results", "Validate extracted schema", "Export structured data"];
    main.innerHTML = `<section class='panel-grid'><div class='card'><div class='card-header'><p class='eyebrow'>Extraction plan</p><h2 style='margin:0;font-size:24px'>${project.name}</h2></div><div class='card-body section-grid'><div class='list'>${steps.map((step, index) => `<div class='list-item'><div><div style='font-weight:700'>Step ${index + 1}</div><div class='inline-meta'><span>${typeof step === "string" ? step : JSON.stringify(step)}</span></div></div><span class='kbd'>${index + 1}</span></div>`).join("")}</div><div class='form-actions'><button class='button' id='runExtraction'>Run extraction</button><button class='button-secondary' id='regeneratePlan'>Regenerate</button><a class='button-ghost' href='/context.html?project=${projectId}'>Edit context</a></div></div></div><div class='card'><div class='card-header'><p class='eyebrow'>Plan inputs</p><h2 style='margin:0;font-size:24px'>Context snapshot</h2></div><div class='card-body section-grid'><div class='list-item'><div><div style='font-weight:700'>Target URL</div><div class='inline-meta'><span>${context.target_url || "Not set"}</span></div></div></div><div class='list-item'><div><div style='font-weight:700'>Fields</div><div class='inline-meta'><span>${(context.fields || []).join(", ") || "None"}</span></div></div></div><div class='list-item'><div><div style='font-weight:700'>Output schema</div><pre style='margin:0'>${ui.escapeHtml(JSON.stringify(context.current_schema || { entity: context.entity || "record", fields: context.fields || [] }, null, 2))}</pre></div></div><div class='list-item'><div><div style='font-weight:700'>Warnings</div><div class='inline-meta'><span>${context.auth_required ? "Target may require credentials." : "No immediate blockers detected."}</span></div></div></div></div></div></section>`;
    main.querySelector("#runExtraction").addEventListener("click", async () => { const job = await api.createJob({ project_id: projectId, conversation_id: conversations[0]?.id || null, status: "queued", job_type: "extraction", config: { fields: context.fields || [], export_format: context.export_format || "json", target_url: context.target_url || null } }); ui.toast(`Job ${job.id} queued`, "success"); window.location.href = `/job.html?project=${projectId}&job=${job.id}`; });
    main.querySelector("#regeneratePlan").addEventListener("click", () => ui.toast("Plan regeneration placeholder triggered. Use the chat page to refine instructions.", "success"));
  });
})();
