(function () {
  const ui = window.ScrapeFlowUI;
  document.addEventListener("DOMContentLoaded", () => {
    const main = ui.shell("settings", "Settings", "Adjust profile details, notification defaults, theme preferences, and platform-level controls.");
    if (!main || !ui.requireAuth()) return;
    const session = ui.currentSession();
    main.innerHTML = `<section class='settings-grid'><div class='card'><div class='card-header'><p class='eyebrow'>Profile</p><h2 style='margin:0;font-size:22px'>Identity</h2></div><div class='card-body'><form id='profileForm' class='section-grid'><div class='field'><label>Name</label><input name='name' value='${ui.escapeHtml(session.name)}'></div><div class='field'><label>Email</label><input name='email' value='${ui.escapeHtml(session.email)}'></div><div class='field'><label>Default export</label><select name='defaultExport'><option>json</option><option>csv</option><option>excel</option></select></div><div class='field'><label>Theme</label><select name='theme'><option>light</option></select></div><div class='form-actions'><button class='button' type='submit'>Save profile</button></div></form></div></div><div class='card'><div class='card-header'><p class='eyebrow'>Platform controls</p><h2 style='margin:0;font-size:22px'>Preferences</h2></div><div class='card-body section-grid'><div class='list-item'><div><div style='font-weight:700'>Mock mode</div><div class='inline-meta'><span>Use local fallback data when backend endpoints are missing.</span></div></div><button class='button-secondary' id='toggleMock'>${window.ScrapeFlowAPI.useMock() ? "Disable" : "Enable"}</button></div><div class='list-item'><div><div style='font-weight:700'>API base URL</div><div class='inline-meta'><span>${window.ScrapeFlowConfig.API_BASE_URL}</span></div></div><button class='button-ghost' id='changeApi'>Change</button></div><div class='list-item'><div><div style='font-weight:700'>Notifications</div><div class='inline-meta'><span>Email and in-app summaries for job state changes.</span></div></div><span class='kbd'>Enabled</span></div></div></div></section>`;
    main.querySelector("#profileForm").addEventListener("submit", (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); ui.setSession({ ...session, name: form.get("name"), email: form.get("email") }); ui.toast("Profile updated locally", "success"); });
    main.querySelector("#toggleMock").addEventListener("click", () => { const next = !window.ScrapeFlowAPI.useMock(); window.ScrapeFlowAPI.setMockMode(next); ui.toast(`Mock mode ${next ? "enabled" : "disabled"}`, "success"); setTimeout(() => window.location.reload(), 400); });
    main.querySelector("#changeApi").addEventListener("click", () => ui.modal({ title: "Change API base URL", body: `<div class='field'><label>Base URL</label><input id='apiBaseField' value='${ui.escapeHtml(window.ScrapeFlowConfig.API_BASE_URL)}'></div>`, confirmText: "Save", onConfirm: async (backdrop) => { localStorage.setItem("sf_api_base_url", backdrop.querySelector("#apiBaseField").value.trim()); ui.toast("API base URL updated", "success"); setTimeout(() => window.location.reload(), 400); } }));
  });
})();
