(function () {
  const key = (name) => `${window.ScrapeFlowConfig.STORAGE_PREFIX}${name}`;
  const routes = [["dashboard", "dashboard.html", "Dashboard", "DB"],["projects", "projects.html", "Projects", "PR"],["jobs", "jobs.html", "Jobs", "JB"],["results", "results.html", "Results", "RS"],["exports", "exports.html", "Exports", "EX"],["settings", "settings.html", "Settings", "ST"]];
  function save(name, value) { localStorage.setItem(key(name), JSON.stringify(value)); }
  function load(name, fallback = null) { const raw = localStorage.getItem(key(name)); return raw ? JSON.parse(raw) : fallback; }
  function toast(message, tone = "info") { let region = document.querySelector(".toast-region"); if (!region) { region = document.createElement("div"); region.className = "toast-region"; document.body.appendChild(region); } const node = document.createElement("div"); node.className = "toast"; node.style.borderLeft = `4px solid ${tone === "error" ? "#dc2626" : tone === "success" ? "#16a34a" : "#2563eb"}`; node.textContent = message; region.appendChild(node); setTimeout(() => node.remove(), 3400); }
  function statusClass(status = "created") { return `status-badge status-${status.toLowerCase()}`; }
  function shell(page, title, subtitle) { const app = document.querySelector("[data-app]"); if (!app) return; app.innerHTML = `<div class="app-shell"><aside class="sidebar"><a class="sidebar-logo" href="/dashboard.html"><div class="logo-mark">SF</div><div><div style="font-weight:700">ScrapeFlow</div><div style="color:var(--text-soft);font-size:13px">Parse++ workspace</div></div></a><nav class="sidebar-nav">${routes.map(([id, href, label, icon]) => `<a class="sidebar-link ${id === page ? "active" : ""}" href="/${href}"><span class="kbd">${icon}</span><span>${label}</span></a>`).join("")}</nav><div class="sidebar-spacer"></div><div class="sidebar-footer"><a class="sidebar-link ${page === "context" ? "active" : ""}" href="/context.html"><span class="kbd">CT</span><span>Context</span></a><a class="sidebar-link ${page === "plan" ? "active" : ""}" href="/plan.html"><span class="kbd">PL</span><span>Plan</span></a><a class="sidebar-link ${page === "chat" ? "active" : ""}" href="/chat.html"><span class="kbd">CH</span><span>Chat</span></a><a class="sidebar-link" href="#" data-logout-link><span class="kbd">LO</span><span>Logout</span></a></div></aside><div class="content-area"><header class="topbar"><div class="topbar-title"><p class="eyebrow">ScrapeFlow Platform</p><h1 class="page-title">${title}</h1><p class="page-subtitle">${subtitle}</p></div><div class="topbar-actions"><button class="button-ghost" type="button" data-toggle-mock>${window.ScrapeFlowAPI.useMock() ? "Mock mode" : "Live API"}</button><a class="button-secondary" href="/docs" target="_blank" rel="noreferrer">API Docs</a><a class="button" href="/projects.html">New project</a></div></header><main class="main-content"></main></div></div>`; app.querySelector("[data-toggle-mock]").addEventListener("click", () => { const next = !window.ScrapeFlowAPI.useMock(); window.ScrapeFlowAPI.setMockMode(next); toast(`Switched to ${next ? "mock" : "live"} mode. Reloading...`, "success"); setTimeout(() => window.location.reload(), 600); }); const logoutLink = app.querySelector("[data-logout-link]"); if (logoutLink) logoutLink.addEventListener("click", (event) => { event.preventDefault(); localStorage.removeItem(key("session")); toast("Logged out", "success"); setTimeout(() => { window.location.href = "/login.html"; }, 250); }); return app.querySelector(".main-content"); }
  function requireAuth() { if (document.body.dataset.public === "true") return true; const session = load("session"); if (!session) { window.location.href = "/login.html"; return false; } return true; }
  function currentSession() { return load("session"); }
  function setSession(session) { save("session", session); }
  function setActiveProject(project) { save("activeProject", project); }
  function getActiveProject() { return load("activeProject"); }
  function setActiveConversation(conversation) { save("activeConversation", conversation); }
  function getActiveConversation() { return load("activeConversation"); }
  function renderList(container, items, renderer, emptyMessage) { if (!items || !items.length) { container.innerHTML = `<div class="empty-state">${emptyMessage}</div>`; return; } container.innerHTML = items.map(renderer).join(""); }
  function modal({ title, body, onConfirm, confirmText = "Confirm", tone = "default" }) { const backdrop = document.createElement("div"); backdrop.className = "modal-backdrop"; backdrop.innerHTML = `<div class="modal"><div class="modal-header"><h3 style="margin:0">${title}</h3></div><div class="modal-body">${body}</div><div class="modal-footer"><button class="button-ghost" type="button" data-close>Cancel</button><button class="${tone === "danger" ? "button-danger" : "button"}" type="button" data-confirm>${confirmText}</button></div></div>`; backdrop.querySelector("[data-close]").addEventListener("click", () => backdrop.remove()); backdrop.addEventListener("click", (event) => { if (event.target === backdrop) backdrop.remove(); }); backdrop.querySelector("[data-confirm]").addEventListener("click", async () => { if (onConfirm) await onConfirm(backdrop); backdrop.remove(); }); document.body.appendChild(backdrop); }
  function formatDate(value) { return value ? new Date(value).toLocaleString() : "-"; }
  function escapeHtml(value) { return String(value ?? "").replace(/[&<>\"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[char])); }
  window.ScrapeFlowUI = { save, load, toast, shell, requireAuth, currentSession, setSession, setActiveProject, getActiveProject, setActiveConversation, getActiveConversation, renderList, modal, formatDate, escapeHtml, statusClass };
})();
